import generate from 'babel-generator';
import traverse from 'babel-traverse';
import {program} from 'babel-types';
import flatten from 'flatten';

const warning = `/* !\n` +
                `   ! Please don't edit this file by hand;\n` +
                `   ! it is automatically generated by the css-values module.\n` +
                `   ! */\n\n`;

export default contents => {
    let script = program(flatten(contents));

    traverse(script, {
        noScope: true,
        EmptyStatement: function (path) {
            path.remove();
        }
    });

    return warning + generate(script).code + '\n';
};
